### ISSUE TITLE
Explore Assembly Languages

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#100]
To be honest, I'm only familiar with like 2 languages: x86 and MIPS. When I poke around the Hello World Collection, I notice that they file all assembly languages under `a` for assembly. Apparently, there are languages, assemblers, and platforms. So, there can be literally any combination of these...

Not sure how I want to handle assembly right now since the programs are platform and assembler dependent. Of course, we can all agree `.asm` is the file extension for everything.

**Comment by jrg94** [comment]
I think I'm just going to make an assembly folder and we can just dump implementations for all the architectures there. Maybe we can have a little fun with it and create folders for each architecture.

**Comment by jrg94** [comment]
Maybe this list of assemblers can help us out: https://en.wikipedia.org/wiki/Comparison_of_assemblers

**Comment by chrboe** [comment]
> Of course, we can all agree .asm is the file extension for everything.

Not necessarily. For instance, gcc uses `.s` (or `.S` for precompiled assembly) extensions.

The problem with this is also syntax; there's AT&T and Intel syntax (that might be what you meant by "languages"), and they're different even though they do the same thing.

Personally, I'd keep it to one syntax and assembler per platform, and have a solution for every platform. These could then be filed under `arm-asm`, `x86-asm`,...

**Comment by jrg94** [comment]
If you decide to take a stab at any of these, I'll be happy to assist in repo structure through a pull request. I don't really know how we'd organize this yet, but I like your idea so far.

**Comment by jrg94** [comment]
We'll deal with this when it happens! Haha
