### ISSUE TITLE
Add Article for Hello World in R

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#102]
Merged code: #101

**Comment by jrg94** [comment]
Added: https://github.com/jrg94/sample-programs/commit/68825604e7ba7b4240c1c89ce2beef974dcc1072

**Comment by awoerner92** [comment]
I'll start working on this if you don't mind.

**Comment by jrg94** [comment]
It's all you 👍

**Comment by awoerner92** [comment]
Draft is finished. I also created a pull request to add the link to the Readme.

What do you think of [this](https://pixabay.com/en/sailboat-boat-marin-corsair-pirate-1273168/) as the featured image?
