### ISSUE TITLE
Add Hello World in Lobster

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1080]
If possible, please provide a link(s) to the language documentation to prove its existence:

- https://github.com/aardappel/lobster

If possible, please provide a code snippet of Hello World in the language:

```lang
print("Hello, World!")
````
source: https://htmlpreview.github.io/?https://raw.githubusercontent.com/aardappel/lobster/master/lobster/docs/command_line_usage.html

**Comment by proabel** [comment]
I will add "hello world" program in lobster.
