### ISSUE TITLE
Update Python Game of Life to Use Canvas

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#110]
Alright, I recently implemented Game of Life in nearly the exact same way as Java. However, I ran into a major UI constraint with tkinter. Apparently, nesting widgets is bad in tkinter. See: #109.

So, at some point, I want to update that implementation to use canvas instead.

**Comment by 2Clutch** [comment]
I'd like to be assigned this issue if nobody else is currently working on it.

**Comment by jrg94** [comment]
It's all yours! I can't officially assign to issue to you for whatever reason. I guess that's [restricted to collaborators](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/).

**Comment by jrg94** [comment]
Updated the issue, so you're officially assigned to it!

**Comment by jrg94** [comment]
This is still something I'd like to revisit, but we'll close this to reduce issue clutter.
