### ISSUE TITLE
Add Hello World in ArkScript

### ISSUE THREAD

**Issue by SuperFola** [TheRenegadeCoder/sample-programs#1119]
ArkScript is a Lisp like scripting language intended to be used in C++ projects, running on its virtual machine.

Documentation: https://arkscript-lang.github.io/documentation.html

```clojure
(print "hello world!")
````

Edit: updating documentation link from wiki to website since we ditched the aforementioned wiki

**Comment by beebus** [comment]
Title and description should be changed where "Ark" appears to "Arc".
[https://en.wikipedia.org/wiki/Arc_(programming_language)](url)

> Hello world in Arc :

` (prn "Hello, World")`

**Comment by beebus** [comment]
Also, the link above, 

> Documentation: [https://github.com/SuperFola/Ark/tree/rework/doc](https://github.com/SuperFola/Ark/tree/rework/doc)

is not working anymore.

**Comment by beebus** [comment]
This is confusing. "Ark" as described by [https://github.com/SuperFola/Ark](https://github.com/SuperFola/Ark) and [https://github.com/ark-lang/ark](https://github.com/ark-lang/ark) is a scripting language (higher level) derived from Go.
I'm not immediately sure how this relates to "Arc" described by the Wikipedia page above.

**Comment by SuperFola** [comment]
ArkScript isn't Arc nor Ark, updating now

**Comment by arjitg** [comment]
Hey @jrg94 I'd like to take this up. Please assign it to me.
It could be a good starting point.

**Comment by SuperFola** [comment]
If you need any help with ArkScript, feel free to hit me up!

**Comment by arjitg** [comment]
hey @jrg94 , https://github.com/TheRenegadeCoder/sample-programs/pull/1741 is PR related to this issue. Check it out.

**Comment by jrg94** [comment]
Looks like you added the article! That's great. Any chance you can add the code as well?

**Comment by arjitg** [comment]
I have added the article as a .md file. Do we have to add a seperate file with the code too? If so, which folder is it under? I'm looking at sample-programs/docs

**Comment by jrg94** [comment]
Yeah, this issue was primarily meant for the code, but the article is awesome! The code would go under `archive/a/arkscript`.

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by SuperFola** [comment]
Hi there, I'll try to take care of this soon

**Comment by jrg94** [comment]
Sounds great!
