### ISSUE TITLE
Bash Files Don't Handle Windows Line Endings

### ISSUE THREAD

**Issue by auroq** [TheRenegadeCoder/sample-programs#1126]
When the repository is checked out on a windows machine, git automatically converts all line endings to windows line endings. When trying to run a bash script using samplerunner, bash files fail to run because of the windows line endings.

Possible solutions:
- Add a .gitattributes entry to make .sh (and maybe other) filetypes check out as linux endings
- Automatically run a tool (such as dos2unix) to convert line endings before sample runner executes
- Modify sample runner to convert line endings as part of container creation

**Comment by jrg94** [comment]
Nice work! Glad you were able to figure this out. That said, why does this issue also happen on Travis CI? I thought that was a Linux-based service?

**Comment by auroq** [comment]
I haven't seen this (bash file) issue on Travis, if it did, it would mean that somehow windows line endings were checked into the repo and checked out as is to Travis. Git by default will convert all line endings to Linux on push and convert them to Windows or Linux as applicable on check pull.

As per issue from #1125, my best guess would be there is a leaky abstraction. `fsharpc` on my Linux machines (both arch Linux) automatically detected that it needed a Linux binary that could be executed from shell. In docker on a windows host or on Travis' Ubuntu host, it for whatever reason did not detect the right binary to compile to. Docker is supposed to abstract out enough to prevent differences like this. It's really good at doing that, but for whatever reason, the abstraction seemed to leak at this level.

**Comment by jrg94** [comment]
Ah! I see. Is this something we could potentially run into on other languages? If so, I’d like to document it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
