### ISSUE TITLE
Add Bubble Sort in C++

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1135]
See requirements: https://sample-programs.therenegadecoder.com/projects/bubble-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

**Comment by jaythras** [comment]
I would love to take this!

**Comment by jrg94** [comment]
It's all yours!

**Comment by dipanshu231099** [comment]
@jrg94 i would also like to add the code

**Comment by jrg94** [comment]
Hey @dipanshu231099! We usually restrict solutions to one per problem. You're welcome to support @jaythras when they make their pull request. 

That said, check [the C++ folder](https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus). There are a ton of programs missing. For a complete list of programs, look here: https://sample-programs.therenegadecoder.com/projects/

You're also welcome to add new programs. Just let me know what you're thinking about! 😄
