### ISSUE TITLE
Add Bubble Sort in Elixir

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1138]
See requirements: https://sample-programs.therenegadecoder.com/projects/bubble-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/e/elixir

**Comment by palaparthi** [comment]
I can take this

**Comment by jrg94** [comment]
It's all yours!

**Comment by palaparthi** [comment]
@jrg94 can you review the PR https://github.com/TheRenegadeCoder/sample-programs/pull/1167
