### ISSUE TITLE
Add Fizz Buzz in Erlang

### ISSUE THREAD

**Issue by mdmagahis** [TheRenegadeCoder/sample-programs#1166]
# Erlang
## Language documentation
- http://erlang.org/erldoc
- https://learnyousomeerlang.com/content

## Code snippet of Hello World in the Erlang:

```erlang
module(hello_world).
-export([start/0]).

start() ->
   io:format("Hello, World!~n", []).
````

**Comment by caioariede** [comment]
I'll be working on this one

**Comment by mdmagahis** [comment]
@caioariede I already have the PR drafted. I got this one
