### ISSUE TITLE
Generate Hacktoberfest Issues

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1169]
Currently, this repo has a ton of missing snippets. For instance, there are [23 supported projects](https://sample-programs.therenegadecoder.com/projects/) and [111 support languages](https://github.com/TheRenegadeCoder/sample-programs/wiki/Alphabetical-Language-Catalog). If you multiply those numbers together, there are potentially 2553 snippets in this collection. At this time, there are only 292 snippets. In other words, *we have room for 2261 snippets*. 

To aid in that effort, I'm looking for some people to begin generating issues for the missing snippets. To get proper coverage throughout October, we'll want to tag those issues with "hacktoberfest," so others can find our open issues quickly. See the following issues as examples:

- #1131
- #1132 
- #1133

If you want to help with this, comment below, so I can add you to the organization. Then, you should be able to generate your own issues AND tag them appropriately.

**Comment by wileymab** [comment]
I'm willing to help out with this.

**Comment by jrg94** [comment]
That would be awesome! I'll be needing some help with merging pull requests as well. This time of the year is always a bit overwhelming.

**Comment by arjitg** [comment]
@jrg94 I would love to contribute.

**Comment by jrg94** [comment]
That would be helpful! It might a good idea if you could comb through the current issues and find duplicates. Right now, we're running into issues where people are submitting code that already exists, so eliminating duplicate issues could help reduce that problem.
