### ISSUE TITLE
Add Captialize in Bash

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1216]
See requirements: https://sample-programs.therenegadecoder.com/projects/capitalize/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/b/bash

**Comment by lohxx** [comment]
I am interested in this issue, can I take it?

**Comment by wileymab** [comment]
@lohxx I believe it's all yours! @jrg94 has permissions to assign it to you explicitly.

**Comment by lohxx** [comment]
Ok, thank you
