### ISSUE TITLE
Add Even Odd in Bash

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1218]
See requirements: https://sample-programs.therenegadecoder.com/projects/even-odd/
Add snipper here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/b/bash

**Comment by wileymab** [comment]
@jrg94 Doesn't appear that I have permissions to add the labels.

**Comment by jrg94** [comment]
Welp! Looks like I'll have to add you to the core group.
