### ISSUE TITLE
Add Even/Odd in C++

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1236]
See requirements: https://sample-programs.therenegadecoder.com/projects/even-odd/
Add snipper here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

**Comment by killbotXD** [comment]
I would like to work on this one.

**Comment by akn264** [comment]
me too

**Comment by jrg94** [comment]
@akn264 we usually in support one snippet per project and language, but you’re welcome to support @killbotXD. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0x6f736f646f** [comment]
Working on it

**Comment by jrg94** [comment]
Hey @0x6f736f646f! Just to be clear, this is already assigned to @killbotXD.

**Comment by 0x6f736f646f** [comment]
👍
i thought no one was working on it
