### ISSUE TITLE
Add Factorial in C++

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1237]
See requirements: https://sample-programs.therenegadecoder.com/projects/factorial/
Add snipper here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

**Comment by killbotXD** [comment]
I would like to work on this one.

**Comment by jrg94** [comment]
Hey @killbotXD! Looks like someone snagged this in #1243. Sorry about that.
