### ISSUE TITLE
Add Fizz Buzz in C++

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1238]
See requirements: https://sample-programs.therenegadecoder.com/projects/fizz-buzz/
Add snipper here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

**Comment by prasunka** [comment]
I would like to work on this.

**Comment by prasunka** [comment]
Hey @jrg94, looks like this issue has been fixed. Kindly close this issue.

**Comment by jrg94** [comment]
It'll automatically close when the pull request is merged.
