### ISSUE TITLE
Add Game of Life in C++

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1239]
See requirements: https://sample-programs.therenegadecoder.com/projects/game-of-life/
Add snipper here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

**Comment by Soniyanayak51** [comment]
I would like to work on this.

**Comment by jrg94** [comment]
Good luck! I appreciate the help.
