### ISSUE TITLE
Add Insertion Sort in C++

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1240]
See requirements: https://sample-programs.therenegadecoder.com/projects/insertion-sort/
Add snipper here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-plus-plus

**Comment by sun-fox** [comment]
I would like to work on this.

**Comment by KushalVijay** [comment]
I would like to work on this.

**Comment by sun-fox** [comment]
#1253 added the insertion sort code and explanation.
