### ISSUE TITLE
Add Selection Sort in C

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1272]
See requirements: https://sample-programs.therenegadecoder.com/projects/selection-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c

**Comment by sourabbr** [comment]
I would like to take on this issue

**Comment by jrg94** [comment]
Be aware that @manotien has created a pull request for this, but they haven't updated it yet.
