### ISSUE TITLE
Add Longest Common Subsequence in C#

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1279]
See requirements: https://sample-programs.therenegadecoder.com/projects/longest-common-subsequence/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-sharp

**Comment by KaterynaKateryna** [comment]
I'd like to take this issue if nobody is working on it

**Comment by jrg94** [comment]
Good catch!
