### ISSUE TITLE
Add Roman Numeral Conversion in C#

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1284]
See requirements: https://sample-programs.therenegadecoder.com/projects/roman-numeral-conversion/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/c-sharp

**Comment by KaterynaKateryna** [comment]
this algorithm already exists: https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/c/c-sharp/RomanNumeral.cs

**Comment by jrg94** [comment]
Nice catch!
