### ISSUE TITLE
Add Even/Odd in CoffeeScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1323]
See requirements: https://sample-programs.therenegadecoder.com/projects/even-odd/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/c/coffeescript

**Comment by shahkv95** [comment]
@wileymab @jrg94 Could you please assign me this issue?
Thank you!

**Comment by suntansoker** [comment]
Hi @jrg94 I will like to work on this

**Comment by shahkv95** [comment]
@jrg94 I have uploaded the pull request. Please merge the same.
Thank you!
