### ISSUE TITLE
Add Reverse A String in Go

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1329]
See requirements: https://sample-programs.therenegadecoder.com/projects/reverse-a-string/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/g/go

**Comment by iwishiwasaneagle** [comment]
This already exists https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/g/go/string-reverse.go
