### ISSUE TITLE
Add Hello World in ALGOL 60

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#135]
[ALGOL 60 Wiki](https://en.wikipedia.org/wiki/ALGOL_60)

**Comment by jrg94** [comment]
@trevershick added ALGOL 68. I'll keep the issue open for ALGOL 60 unless this implementation covers both languages.

**Comment by trevershick** [comment]
Honestly I don’t know but the only runtime I found was for 68. I think it’s like having a c++ 11 vs 14. Same core language but upgraded? Maybe.

**Comment by jrg94** [comment]
Makes sense. I've only kept them separated because they typically are in other collections I've seen:

- http://helloworldcollection.de/
- https://github.com/leachim6/hello-world

**Comment by jrg94** [comment]
They even have separate wiki pages for some reason.

**Comment by trevershick** [comment]
yeah. different versions of the language i take it. i think it makes sense to keep the old issue open

**Comment by martyav** [comment]
Looks like Algol60 would present a special challenge:

> Because the Algol 60 document did not provide for any I/O, it was provided in ad-hoc ways by various compiler writers. No two I/O systems were compatible with one another, so it was not possible to write a "Hello World" program that would run on more than one implementation.

[Source: Peter M. Maurer](http://cs.ecs.baylor.edu/~maurer/SieveE/Algol60.htm)

**Comment by jrg94** [comment]
For our purposes then, I think we can close this issue out.
