### ISSUE TITLE
Add Capitalize in Haskell

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1356]
See requirements: https://sample-programs.therenegadecoder.com/projects/capitalize/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/h/haskell

**Comment by csrunner20** [comment]
Hello, I'm interested in Haskell and this seems like a cool project, can I take this issue?

**Comment by jrg94** [comment]
It's all you! 👍
