### ISSUE TITLE
Add Roman Numeral Conversion in Haskell

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1360]
See requirements: https://sample-programs.therenegadecoder.com/projects/roman-numeral-conversion/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/h/haskell

**Comment by csrunner20** [comment]
Hey @auroq just checking out some other Haskell issues.  And I think this code already exists: https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/h/haskell/roman-numeral.hs

So perhaps this issue can be closed already...

**Comment by jrg94** [comment]
You're right! This was completed 7 months ago.
