### ISSUE TITLE
Add Capitalize in Java

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1366]
See requirements: https://sample-programs.therenegadecoder.com/projects/capitalize/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/java

**Comment by Shubham230198** [comment]
I would like to work on it.

**Comment by jrg94** [comment]
I think this already got merged #1580, but we forgot to close it.
