### ISSUE TITLE
Add Minimum Spanning Tree in Java

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1368]
See requirements: https://sample-programs.therenegadecoder.com/projects/minimum-spanning-tree/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/java

**Comment by Shubham230198** [comment]
I will work on it.

**Comment by LezendarySandwich** [comment]
I will work on it.
