### ISSUE TITLE
Add Merge Sort in Java

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1371]
See requirements: https://sample-programs.therenegadecoder.com/projects/merge-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/java

**Comment by Shubham230198** [comment]
I would like to work on it.

**Comment by raj808569** [comment]
Getting failed tests for factorial.ex

**Comment by jrg94** [comment]
Should be fixed now.
