### ISSUE TITLE
Add Prime Number in Java

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1372]
See requirements: https://sample-programs.therenegadecoder.com/projects/prime-number/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/java

**Comment by EwertonQueiroz** [comment]
Solution #1547

**Comment by enkaranfiles** [comment]
all we have to do is writing code snippet for Java Prime Number?

**Comment by jrg94** [comment]
Yup! Exactly.

**Comment by Shubham230198** [comment]
Can I work on it.

**Comment by jrg94** [comment]
It looks like a lot of folks are trying to work on this. At this point, I'll merge whatever passes testing.
