### ISSUE TITLE
Add Longest Common Subsequence in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1381]
See requirements: https://sample-programs.therenegadecoder.com/projects/longest-common-subsequence/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by 13point5** [comment]
I want to work on this

**Comment by suntansoker** [comment]
Hi @jrg94 I will like to work on this.

**Comment by suntansoker** [comment]
I think we can close this issue. It has been closed in the issue #2129
