### ISSUE TITLE
Add Minimum Spanning Tree in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1386]
See requirements: https://sample-programs.therenegadecoder.com/projects/minimum-spanning-tree/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by nikkkhil067** [comment]
@wileymab I can do this, so please assign this to me.

**Comment by shahkv95** [comment]
@wileymab @jrg94 Could I please work on this issue?
Thank you!
