### ISSUE TITLE
Add Prime Number in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1387]
See requirements: https://sample-programs.therenegadecoder.com/projects/prime-number/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by anil-goudar** [comment]
@wileymab Please assign this issue for me.

**Comment by seanmfox** [comment]
Mind if I take this issue?

**Comment by legowerewolf** [comment]
@seanmfox still working on this? I wrote a solution for quickly finding primes awhile ago, but if you still want to claim this go ahead.

**Comment by komputarist** [comment]
Mind if I take this issue? @jrg94 ?

**Comment by jrg94** [comment]
Sorry! I think this issue was accidentally duplicated. I'll close it now.
