### ISSUE TITLE
Add Quick Sort in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1388]
See requirements: https://sample-programs.therenegadecoder.com/projects/quick-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by sanjaypradeep** [comment]
PR is been raised!

**Comment by jrg94** [comment]
I think this issue was duplicated. This solution already exists.
