### ISSUE TITLE
Add Job Sequencing with Deadlines in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1389]
See requirements: https://sample-programs.therenegadecoder.com/projects/job-sequencing-with-deadlines/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by suntansoker** [comment]
Hi @jrg94, I will work on this

**Comment by suntansoker** [comment]
Closed in issue #2163
