### ISSUE TITLE
Add File IO in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1390]
See requirements: https://sample-programs.therenegadecoder.com/projects/file-io/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by gmananan** [comment]
Is Node.js allowed here, or is it limited to JS in the browser?

**Comment by wileymab** [comment]
I would assume Nodejs is fair gane. I think file access from the browser takes special permissions that would be out of scope for this project. @jrg94 thoughts?

**Comment by jrg94** [comment]
Yup! Actually JS is exclusively Node in this repo since we try to handle everything over the command line for testing purposes.
