### ISSUE TITLE
Add Even/Odd in JavaScript

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1392]
See requirements: https://sample-programs.therenegadecoder.com/projects/even-odd/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/j/javascript

**Comment by gmananan** [comment]
This seems really easy. Should I take it, or do you want to add a label like 'good first issue' for someone new?

I think it might make a good first PR for someone.

**Comment by jrg94** [comment]
You can snag it! There's plenty of issues to go around.
