### ISSUE TITLE
Add Factorial in Kotlin

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1399]
See requirements: https://sample-programs.therenegadecoder.com/projects/factorial/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/k/kotlin

**Comment by shahkv95** [comment]
@wileymab Can I work on this issue? 
Thank you!

**Comment by shahkv95** [comment]
@wileymab @jrg94 Could you please merge this pull request.
So that I can solve the other assigned issues as well.

Thank you so much!

**Comment by jrg94** [comment]
You can make branches on your repo and make pull requests for each branch. There's no guarantee well be able to get to the request quickly.
