### ISSUE TITLE
Add Merge Sort in Kotlin

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1401]
See requirements: https://sample-programs.therenegadecoder.com/projects/merge-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/k/kotlin

**Comment by shahkv95** [comment]
@wileymab @jrg94  Can I work on this issue?
Thank you!

**Comment by jrg94** [comment]
It looks like @mikenmo may have already submitted a solution.
