### ISSUE TITLE
Add Minimum Spanning Tree in Kotlin

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1408]
See requirements: https://sample-programs.therenegadecoder.com/projects/minimum-spanning-tree/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/k/kotlin

**Comment by shahkv95** [comment]
@wileymab @jrg94 Can I work on this issue?
Thank you!
