### ISSUE TITLE
Add Job Sequencing with Deadlines in Kotlin

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1409]
See requirements: https://sample-programs.therenegadecoder.com/projects/job-sequencing-with-deadlines/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/k/kotlin

**Comment by smallblack9** [comment]
Hi, I'm new to Hecktoberfest, may I try to contribute to this issue? (If yes, do you have any prefered naming convention for the file name?)

**Comment by jrg94** [comment]
Yup! Double check the contributing doc: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md

That said, I don't think we have any current naming conventions for Kotlin. If you'd like, I think Kotlin could benefit from having the naming conventions standardized.
