### ISSUE TITLE
Add Prime Number in Lua

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1442]
See requirements: https://sample-programs.therenegadecoder.com/projects/prime-number/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/l/lua

**Comment by renato04** [comment]
I would like to work on this

**Comment by renato04** [comment]
It is already done!

**Comment by jrg94** [comment]
Thanks for calling that out. Some of these issues are duplicate.
