### ISSUE TITLE
Add Fizz Buzz in Matlab

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1462]
See requirements: https://sample-programs.therenegadecoder.com/projects/fizz-buzz/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/m/matlab

**Comment by sakurakhadag** [comment]
Can I use an inbuilt function?

**Comment by jrg94** [comment]
Yeah, that's fine!

**Comment by niranjantuty** [comment]
I would like to contribute.  Can I work on this?

**Comment by darkpanda08** [comment]
I have opened the pull request #1901 fixing this issue.

**Comment by jrg94** [comment]
Sorry @niranjantuty! I wasn't up to assign it. I'll reach out if the other script doesn't work out.
