### ISSUE TITLE
Add Hello World in Nice

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#147]
[Nice Wiki](https://en.wikipedia.org/wiki/Nice_(programming_language))

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by JavaVista** [comment]
I will like to give this one a try.

**Comment by JavaVista** [comment]
Looks like this language is no longer supported. I ran a hello world example and the compiler has bug. There is open issue for this bug that has being open for a while https://sourceforge.net/p/nice/bugs/167/.  I am afraid I will not be able to complete this. I will try work on another language in your list for now.
