### ISSUE TITLE
Add Factorial in Objective-C

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1495]
See requirements: https://sample-programs.therenegadecoder.com/projects/factorial/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/o/objective-c

**Comment by apurav10** [comment]
i wanna work on it.

**Comment by rahulkranjan** [comment]
Can I Work on this?

**Comment by jrg94** [comment]
I believe this was submitted.
