### ISSUE TITLE
Add Prime Number in Perl

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1507]
See requirements: https://sample-programs.therenegadecoder.com/projects/prime-number/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/perl

**Comment by SourabhBadhya** [comment]
I would like to take this issue. Please assign it to me.

**Comment by Ayush7-BIT** [comment]
Hey! Can i work on this issue? If possible,please assign me this....
