### ISSUE TITLE
Add Fibonacci in Perl

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1514]
See requirements: https://sample-programs.therenegadecoder.com/projects/fibonacci/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/perl

**Comment by Neilblaze** [comment]
Is it about showing the Fibonacci series upto a range or adding all the Fibonacci numbers upto a range?

Can you assign me regarding this?

**Comment by jrg94** [comment]
Hey @Neilblaze! If you dig into the documentation linked above, you should see exactly the expected output. That said, it should look something like the following:

```
1: 1
2: 1
3: 2
4: 3
5: 5
```

**Comment by Ayush7-BIT** [comment]
Hey! Can i work on this issue? If possible,please assign me this....
