### ISSUE TITLE
Add Selection Sort in Perl

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1515]
See requirements: https://sample-programs.therenegadecoder.com/projects/selection-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/perl

**Comment by fant0me** [comment]
@array = (1,45,10,35,100,13,147,500,80);
$size = @array;
$min = 0;

for ($i = 0; $i < $size ; $i=$i+1){
    
    for($j = $i+1  ; $j < $size ; $j=$j+1){
        
        if($array[$j] < $array[$i]){
            
            $min = $array[$j];
            $array[$j] = $array[$i];
            $array[$i] = $min;
            
        }
    }
    
    break;
    
}

foreach $number (@array){
    
print $number. "
";
    
}

**Comment by jrg94** [comment]
Looks good for the most part! Did you want to submit this as a pull request?

**Comment by fant0me** [comment]
yes

**Comment by Ayush7-BIT** [comment]
Hey! Can i work on this issue? If possible,please assign me this....
