### ISSUE TITLE
Add Merge Sort in PHP

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1521]
See requirements: https://sample-programs.therenegadecoder.com/projects/merge-sort/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/php

**Comment by ironsigma** [comment]
looks like this one is done and merged to master by Ankit Kumar (135af0c60) and Parker Johansen (39eebc1d6)

**Comment by jrg94** [comment]
Good call!
