### ISSUE TITLE
Add ROT-13 in PHP

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1530]
See requirements: https://sample-programs.therenegadecoder.com/projects/rot-13/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/php

**Comment by scove** [comment]
Is this issue still open or does the current ROT-13 function in the archives satisfy the issue?

**Comment by jrg94** [comment]
Good call! It looks like this is already done.
