### ISSUE TITLE
Add Longest Common Subsequence in PHP

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1531]
See requirements: https://sample-programs.therenegadecoder.com/projects/longest-common-subsequence/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/php

**Comment by pranavbharadwaj007** [comment]
I would like to contribute to this issue

**Comment by jrg94** [comment]
It's all yours!
