### ISSUE TITLE
Add Job Sequencing with Deadlines in Python

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1537]
See requirements: https://sample-programs.therenegadecoder.com/projects/job-sequencing-with-deadlines/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/python

**Comment by supriyanta** [comment]
I want to work on it....

**Comment by jrg94** [comment]
Already implemented. Sorry about that.
