### ISSUE TITLE
Add Longest Common Subsequence in Python

### ISSUE THREAD

**Issue by wileymab** [TheRenegadeCoder/sample-programs#1540]
See requirements: https://sample-programs.therenegadecoder.com/projects/longest-common-subsequence/
Add snippet here: https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/p/python

**Comment by Shubham230198** [comment]
i want work on this, can you assign me this.

**Comment by muktadirkhan889** [comment]
I did this @wileymab here: https://github.com/TheRenegadeCoder/sample-programs/pull/1612

**Comment by jrg94** [comment]
Apologies for everyone who keeps working on this. We already have it completed.

**Comment by muktadirkhan889** [comment]
You should have closed it.

**Comment by jrg94** [comment]
It actually got opened in error. It's been a part of the collection since March 21st.
