### ISSUE TITLE
Add Hello World in Kafe

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#155]
[Kafe GitHub](https://github.com/SuperFola/Kafe)

**Comment by mraza007** [comment]
I can do that too please assign this issue to me

**Comment by SuperFola** [comment]
Hi @mraza007 !

I am the developper of Kafe. Currently, the language isn't ready (we only have a virtual machine to run bytecode), but I'll let you know when the first compiler for the language will be released 😄

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by jrg94** [comment]
Still seems in early development. Hoping for updates eventually.
