### ISSUE TITLE
Fix Invalid link of the subscription page of the Renegade Coder!

### ISSUE THREAD

**Issue by Neilblaze** [TheRenegadeCoder/sample-programs#1560]
Here the circled link in the README.md isn't working or might be broken. Please fix this issue asap!
On clicking the circled link, it directs to a page where it pops out - "Oops! That page can’t be found."

![subscribe](https://user-images.githubusercontent.com/48355572/66592447-ab2bef00-ebb2-11e9-8066-f21b704926a2.JPG)

**Comment by jrg94** [comment]
Good catch. You can through [my Patreon](https://www.patreon.com/TheRenegadeCoder) there or [my newsletter](https://newsletter.therenegadecoder.com/).
