### ISSUE TITLE
Add Hello World in Pikelet

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#163]
[Pikelet Official Website](https://brendanzab.github.io/pikelet/)

**Comment by CarlesKapy** [comment]
The previous link is broken.
[Pikelet Language Book](https://pikelet-lang.github.io/pikelet/)
[Pikelet Language Repo](https://github.com/pikelet-lang/pikelet)

**Comment by jrg94** [comment]
Nice catch!

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/
