### ISSUE TITLE
Add Quick Sort in JavaScript

### ISSUE THREAD

**Issue by Gurmeet22** [TheRenegadeCoder/sample-programs#1649]

**Comment by SimplyComplexable** [comment]
@Gurmeet22 This doesn't have the hacktoberfest label, but I'm happy to help with this one if needed.

**Comment by SimplyComplexable** [comment]
Actually just realized this is a duplicate of #1388.

**Comment by jrg94** [comment]
Good point! This actually has two open pull requests, but the one reference in #1388 is pretty far off the mark.
