### ISSUE TITLE
Hacktoberfest Damage Control

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1663]
In November, we're going to need to do some repo cleanup. Since there have been so many pull requests, I've been a bit lax in my adherence to the requirements. Obviously, that means I'm just kicking the can down the road, but otherwise I feel like we'd never get anything merged.

At any rate, I think @auroq has done a great job helping with testing, and I want to start expanding that for more projects and languages. That way, we can ensure consistency across the repo.

Feel free to use this issue to sort of list things you'd like to clean up.

**Comment by jrg94** [comment]
One thing I'd like to do is alphabetize the READMEs for each language. I've started to do it for some of the more popular languages, but it's not consistent across the board.

**Comment by jrg94** [comment]
In addition, I haven't done a great job of enforcing article issues (mostly because I hate watching the issue count climb).

**Comment by auroq** [comment]
Definitely a need for this due to all the attention we've had recently. However, more than that, I would love to discuss the future of this project. I think it would be great to get on a video call and give all interested parties a chance to help create a roadmap for the future of this project.

**Comment by jrg94** [comment]
Yeah, that works for me. I'd be happy to meet after some of this chaos winds down.

**Comment by stuin** [comment]
I will probably stick around a bit this time, track down a few more of those random inconsistencies. It is an interesting project to be involved in.

**Comment by jrg94** [comment]
Glad to have your help! A project this broad is bound to have some issues, and it takes folks like you to  hunt them down.

**Comment by jrg94** [comment]
In the process of cleaning up pull requests for the time being.
