### ISSUE TITLE
Add Insertion-Sort in Matlab

### ISSUE THREAD

**Issue by abh1jeet-devil** [TheRenegadeCoder/sample-programs#1745]
If possible, please provide a link(s) to the language documentation to prove its existence:

- https://example-lang.com

If possible, please provide a code snippet of Hello World in the language:

```lang
...
````

**Comment by Surya97** [comment]
Is this issue open? Can I work on this issue?

**Comment by Ayush7-BIT** [comment]
Hey! Can i work on this issue? If possible,please assign me this....
