### ISSUE TITLE
Add Binary Search in JavaScript

### ISSUE THREAD

**Issue by abh1jeet-devil** [TheRenegadeCoder/sample-programs#1747]
If possible, please provide a link(s) to the language documentation to prove its existence:

- https://example-lang.com

If possible, please provide a code snippet of Hello World in the language:

```lang
...
````

**Comment by neckenth** [comment]
I can take this on :)

**Comment by sudhir512kj** [comment]
Hello @jrg94 I would like to work on this.

**Comment by jrg94** [comment]
I think this has been submitted twice.

**Comment by Ayush7-BIT** [comment]
Hey! Can i work on this issue? If possible,please assign me this....
