### ISSUE TITLE
Issue management suggestion: label issues by language, so potential contributors can find langs they know.

### ISSUE THREAD

**Issue by legowerewolf** [TheRenegadeCoder/sample-programs#1751]
Title.

**Comment by jrg94** [comment]
I'd be interested in doing something like this, but there are already so many labels. Instead, we try to have a more consistent naming scheme for issues. In other words, you should be able to search for your language of choice (i.e. Python) and get what you want.

**Comment by legowerewolf** [comment]
😂😂😂 I realized this 5 seconds after I created the issue.

**Comment by jrg94** [comment]
That's good to know! Glad you were able to figure things out. Let me know if we can still do better.
