### ISSUE TITLE
Add Capitalize in Rust

### ISSUE THREAD

**Issue by msj2** [TheRenegadeCoder/sample-programs#1781]
rust language is a strictly typed language, much sought for memory-safety & performance.
I am proposing to add 
If possible, please provide a link(s) to the language documentation to prove its existence:

- https://doc.rust-lang.org/1.30.0/book/first-edition/getting-started.html

If possible, please provide a code snippet of Hello World in the language:

```fn main() {
    println!("Hello, world!");
}
...
````

Note: I want to add 3 different programs in 1 pull request, as I fear adding only 1 program is going to get counted as very weak one in code-quality for Hacktoberfest.
Kindly approve.

**Comment by msj2** [comment]
Hi Jeremy, 

Thanks to your guidance & support, I made it thru Hacktober fest 2019.

Passing thru the Travis.CI is addictive.
this year, I wrote small one's.

I'm coming to this each week.

& I'll get better.

ಧನ್ಯವಾದಗಳು 
Thank you in Kannada language.
-msj2.

**Comment by jrg94** [comment]
Of course, we're happy to have you! 😄
