### ISSUE TITLE
Add Dijkstra Algorithm in C++

### ISSUE THREAD

**Issue by fuboki10** [TheRenegadeCoder/sample-programs#1796]

**Comment by fuboki10** [comment]
#1797

**Comment by jrg94** [comment]
Great idea! We don't currently support his algorithm. Any chance you can help us document it?

**Comment by fuboki10** [comment]
ok i will work on it

**Comment by jrg94** [comment]
Here's the list of projects for more examples: https://sample-programs.therenegadecoder.com/projects/

**Comment by fuboki10** [comment]
#1808
