### ISSUE TITLE
`even-odd.sh` does not get executed by test runner

### ISSUE THREAD

**Issue by daveloyall** [TheRenegadeCoder/sample-programs#1817]
Hello.

I noticed that [`evenodd.sh`](https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/b/bash/odd-even.sh) wasn't being run by [the continuous build service](https://travis-ci.com/TheRenegadeCoder/sample-programs)--that is, it isn't being run through the tests.

Then I noticed that it wasn't using [the "hyphen" naming scheme](https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md#source-files).

I figured that there was a causal relationship between those two facts, so I [renamed it](https://github.com/TheRenegadeCoder/sample-programs/pull/1815/commits/9c25f902738cb8bcccc7980fca61fe408137cb59).

Well, the tests still aren't running for that `even-odd.sh` script.  I looked around, but I wasn't able to figure out why not.

**Comment by jrg94** [comment]
Turns out the name is in the wrong order.
