### ISSUE TITLE
Add MATLAB Testing

### ISSUE THREAD

**Issue by daveloyall** [TheRenegadeCoder/sample-programs#1819]
I see `archive/m/matlab` with some Code Snippets, but there is no `testinfo.yml` there!

**Comment by jrg94** [comment]
Yeah, this one is tough! If you know of a MATLAB docker image, that would be awesome. Otherwise, we might have to leverage Octave or something similar.

**Comment by daveloyall** [comment]
Yes, that's a good idea.  Using [GNU Octave](https://www.gnu.org/software/octave/) instead of [Matlab](https://www.mathworks.com/company/aboutus/contact_us/contact_sales.html) is a good idea!

**Comment by jrg94** [comment]
Looks like there is an octave image: https://hub.docker.com/r/compdatasci/octave-desktop

It's fairly large (about 600 MB), so that may prove to be an issue.

**Comment by daveloyall** [comment]
Looks like that image is based on Ubuntu.  Looks like Octave is generally used under Xwindows.

Somebody provided [a recipe for building an Octave docker image based on Debian (Jessie)](https://github.com/MATPOWER/matpower/blob/master/docker/MATPOWER-Docker.md).  Might be smaller.

I'm not a Docker user nor an Octave user, so I think this path ends here for me.  Good luck!
