### ISSUE TITLE
Add Hello World in Luna

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#185]
Source: https://github.com/luna/luna

**Comment by milg15** [comment]
I've been wanting to check this language. I would like to do this.

**Comment by jrg94** [comment]
It's all yours! Let me know if you need any help getting started.

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by valterm** [comment]
Hi, this has been sitting open for over a year since someone claimed it. Could I please try my hand at it?

**Comment by jrg94** [comment]
It seems Luna turned into enso. It seems very popular but also quite novel. I don't know how to include it at this time.
