### ISSUE TITLE
Add Hello World in Whiley

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#186]
Source: https://github.com/Whiley/WhileyCompiler

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by valterm** [comment]
Hi, I'd like to work on this. Could it please be assigned to me?

**Comment by jrg94** [comment]
Lots of docs here. That said, too much effort for the moment.
