### ISSUE TITLE
Add Hello World in Modula 2

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1872]
Also, got this from Ben (see #1868).

If possible, please provide a link(s) to the language documentation to prove its existence:

- https://example-lang.com

If possible, please provide a code snippet of Hello World in the language:

```modula
MODULE HelloWorld;
IMPORT IO, PRINTF;
BEGIN
  (* Two different ways *)
  PRINTF.PrintF1(%s", "Hello world!");
  IO.WrStr("Hello world!" + CHR(13) + CHR(10));
END HelloWorld.
````

### Explanation

Breaking it down
Modula 2 is a block structured language

Could have imported only the required functions, i.e.
MODULE HelloWorld;
FROM PRINTF IMPORT PrintF1;
FROM IO IMPORT WrStr;
BEGIN
  (* Two different ways *)
  PrintF1(%s", "Hello world!");
  WrStr("Hello world!" + CHR(13) + CHR(10));
END HelloWorld.

To run
Compile in the IDE
Execute the *.exe file

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by shashank-kv** [comment]
Hey. Could you assign this issue to me? So basically just a Hello World code snippet in Modula 2 must be added right?

**Comment by Ayush7-BIT** [comment]
Hey! can i work on this issue? If possible please assign me this..
