### ISSUE TITLE
Add Linear Search Testing

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1887]
Please link the existing project documentation (e.g. [Linear Search](https://sample-programs.therenegadecoder.com/projects/linear-search/)):
- https://sample-programs.therenegadecoder.com/projects/linear-search/

**Comment by sudhir512kj** [comment]
Hello @jrg94 I would like to work on this.

**Comment by Amrita211** [comment]
Hello @jrg94 I would like to work on this issue, can you please assign it to me.
Thanks!

**Comment by jrg94** [comment]
It looks like @sudhir512kj is working on it, but you're welcome to work it out with them.

**Comment by jrg94** [comment]
I think this got solved at some point. #2068
