### ISSUE TITLE
Any Ideas for the Use of HarperDB?

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#1896]
The folks at HarperDB reached out to me about possibly trying out their tools. I don't code enough in my spare time to try to make use of it, but I figured someone in our community could. Here's their [PythonSDK](https://pypi.org/project/harperdb/). Perhaps we could use it in this (or related) projects!

Also, I might blast this off to our Discord as well.

**Comment by sudhir512kj** [comment]
Hello @jrg94 I would like to work on this.

**Comment by hamzzy** [comment]
i'm interested

**Comment by prabin123-proo** [comment]
can i work with you :)

**Comment by Priyansh2001here** [comment]
can you please elaborate more

**Comment by echobash** [comment]
What are the function points on which we can make our contributions? Seen the SDK and functions.

**Comment by jrg94** [comment]
Well that's a good question! Mainly I'm just looking for ideas. How might we use it for this project or others?

**Comment by sshekhar3000** [comment]
I am interested

**Comment by urmila-24** [comment]
hello @jrg94  i would like to work with you

**Comment by Nishanthravula** [comment]
Hello @jrg94 I can work with it

**Comment by thefitcoder** [comment]
I would like to work with you

**Comment by jrg94** [comment]
I'm happy y'all want to work on this, but I was thinking we could use this space to discuss what we could do! Let me know if you have any ideas.
