### ISSUE TITLE
Add 99 Bottles in Python

### ISSUE THREAD

**Issue by Atharv-Attri** [TheRenegadeCoder/sample-programs#1975]
Please link the documentation for this project in the space below (note: don't 
forget to remove the backticks). To find the existing list of supported projects, 
[look here][1]:

Add the program 99 bottles in python. It is called 99 cups of coffee because I feel programmers relate to that more.

**Comment by jrg94** [comment]
Sounds very cool! We don't currently support this program, but I like the idea. We'd need to document it!

**Comment by Atharv-Attri** [comment]
What can I do to get it documented?

**Comment by jrg94** [comment]
It would go somewhere in here: https://github.com/TheRenegadeCoder/sample-programs-website/tree/master/projects

Here's the template we recommend using: https://github.com/TheRenegadeCoder/sample-programs-website/blob/master/templates/PROJECT_ARTICLE_TEMPLATE.md
