### ISSUE TITLE
Add Banker's Algorithm in Python

### ISSUE THREAD

**Issue by Mihir2527** [TheRenegadeCoder/sample-programs#2021]
Please link the documentation for this project in the space below (note: don't 
forget to remove the backticks). To find the existing list of supported projects, 
[look here][1]:

`[Project Link](https://repl.it/@MihirMahajani/Bankers-Algorithm)`

If this code snippet adds a new language to the repo, please provide a link(s) to the 
language documentation to prove its existence in the space below. Feel free to omit
this section otherwise.

`[Project Documentation](https://example-lang.com)`

[1]: https://sample-programs.therenegadecoder.com/projects/

**Comment by abhhii** [comment]
Hi @Mihir2527 can I take up this issue?

**Comment by Mihir2527** [comment]
Yes I'll do it

**Comment by jrg94** [comment]
This is not currently supported. Let me know if you'd like to help with documentation and testing.
