### ISSUE TITLE
Add Counting Sort in Java

### ISSUE THREAD

**Issue by TeraSurror** [TheRenegadeCoder/sample-programs#2026]
Please link the documentation for this project in the space below (note: don't 
forget to remove the backticks). To find the existing list of supported projects, 
[look here][1]:

`[Project Link](https://sample-programs.therenegadecoder.com/projects/some-project)`

If this code snippet adds a new language to the repo, please provide a link(s) to the 
language documentation to prove its existence in the space below. Feel free to omit
this section otherwise.

`[Project Documentation](https://example-lang.com)`

**Comment by ShantanuTaro** [comment]
Hey, I would like to work on this task. Assign it to me.

**Comment by TeraSurror** [comment]
@jrg94 I have added counting sort in java. Can you please review my PR.

**Comment by jrg94** [comment]
We don't currently support this program. Let me know if you'd like to help with documentation and testing.

**Comment by TeraSurror** [comment]
Hey @jrg94 

I would love to work with documentation.

**Comment by jrg94** [comment]
Head over here: https://github.com/TheRenegadeCoder/sample-programs-website

You can take a look at some of the existing pull requests for inspiration. If I have a chance, I'll pass more notes along.
