### ISSUE TITLE
Add Kadane's Algorithm in Python

### ISSUE THREAD

**Issue by 000Nobody** [TheRenegadeCoder/sample-programs#2054]
Kadane's algorithm is a useful algorithm that, given an array, finds the largest sum of a contiguous subarray

**Comment by 000Nobody** [comment]
Can I be assigned this issue?

**Comment by Senpai1199** [comment]
I would like to work on this.

**Comment by JoshuaOloton** [comment]
I'll work on this

**Comment by jrg94** [comment]
Definitely going to need to get this one documented (It's in progress here: https://github.com/TheRenegadeCoder/sample-programs-website/pull/340)
