### ISSUE TITLE
Add LRU Cache in Python

### ISSUE THREAD

**Issue by Senpai1199** [TheRenegadeCoder/sample-programs#2058]
This is one of the most popular caching algorithms and I think implementing it in Python would be very useful.

**Comment by Ask-Subhasmita** [comment]
Hello @Senpai1199, I would like to work on it can you assign me this issue?

**Comment by NHema** [comment]
Hi @Senpai1199, can you please assign this to me?

**Comment by Luv8436** [comment]
Hii @Senpai1199 , i am beginning my open source contribution journey , can you assign this issue to me.

**Comment by jrg94** [comment]
Definitely going to need to get this documented.
