### ISSUE TITLE
Add GCD in C++

### ISSUE THREAD

**Issue by VyomGarg47** [TheRenegadeCoder/sample-programs#2088]
Finding GCD of given 2 numbers is a very common task for lots of programs.

**Comment by VyomGarg47** [comment]
Can I work on this issue ?

**Comment by MonarchChakri** [comment]
Can you please let me know if I can work on this.

**Comment by jrg94** [comment]
We don't currently support this: https://sample-programs.therenegadecoder.com/projects/
