### ISSUE TITLE
Add Tree Traversals in Python

### ISSUE THREAD

**Issue by zenithexpo** [TheRenegadeCoder/sample-programs#2095]
Inorder, Preorder and Postorder in Python

**Comment by zenithexpo** [comment]
Can I work on tree traversals? please assign this to me.

**Comment by NHema** [comment]
Can you please assign this to me?

**Comment by jrg94** [comment]
Sounds good! I recommend taking a peek at the DFS project for a place to start on these. They will need to be documented first. 

https://sample-programs.therenegadecoder.com/projects/depth-first-search/

**Comment by zenithexpo** [comment]
Okay, I will start to contribute to it, should I document the tree traversal?

**Comment by jrg94** [comment]
Well, these are a bit tricky because they involve data structures. As a result, other programming languages will likely have to generate their own.

**Comment by zenithexpo** [comment]
Yeah, but we can make a general document which includes basic definitions, how it is implemented and make sure every code is well commented in different programming languages. Just For. eg why is a node created, like basic functionality and description of classes and methods in comments. So that user can get the idea by just going through the code and basic document.

**Comment by jrg94** [comment]
True! A document like that might be helpful. Generally, we work in code snippets though, so I'm not sure tree traversals are a good fit unless you can represent them using an adjacency matrix or some other list-like representation. At the end of the day, all of the code snippets in this repo have to work via the command line, and we haven't tried handling data more complicated than strings. Perhaps in the future we may be able to support files like JSON or something like that.
