### ISSUE TITLE
Update Fizz Buzz in Python to Address Performance Issues

### ISSUE THREAD

**Issue by xPolar** [TheRenegadeCoder/sample-programs#2118]
I want to redo the current Fizz Buzz in Python program as it's inefficient and can be improved.

[Project Link](https://sample-programs.therenegadecoder.com/projects/fizz-buzz/t)

**Comment by jrg94** [comment]
Totally fine! Just make sure it passes testing.

**Comment by xPolar** [comment]
Hey, @jrg94 could you further explain how to test my pull request, kind of confused.

**Comment by jrg94** [comment]
When you submit a pull request, it should test the code for you. That said, you can check out the contributing doc for more details on how to test locally: https://github.com/TheRenegadeCoder/sample-programs/blob/master/.github/CONTRIBUTING.md
