### ISSUE TITLE
Add Kotlin Testing

### ISSUE THREAD

**Issue by smallblack9** [TheRenegadeCoder/sample-programs#2190]
To request a new language, please fill out the following:

Language name:  Kotlin
Official Language Style Guide: https://kotlinlang.org/docs/reference/coding-conventions.html
Official Language Website: https://kotlinlang.org/
Non-Official Language Docker Image: https://hub.docker.com/r/zenika/kotlin

**Comment by jrg94** [comment]
Hey @smallblack9! It looks like another Kotlin solution was included from here #2070. I'm going to do a quick pass of all the files right now and make sure their names are correct.

**Comment by smallblack9** [comment]
@jrg94 Cool, thank you for letting me know. I just synced my fork, I'll keep updating the existing codes and checking all the files in the folder before I create PR.
