### ISSUE TITLE
Incorrect Links in Lolcode README

### ISSUE THREAD

**Issue by Sudhanshu-Dubey14** [TheRenegadeCoder/sample-programs#2200]
The [README of Lolcode](https://github.com/TheRenegadeCoder/sample-programs/tree/master/archive/l/lolcode) has links of Lua docs in References section.

Please correct the links.

**Comment by Mehrapi** [comment]
Hallo, I have sent a PR for this.

**Comment by Sudhanshu-Dubey14** [comment]
Hey @Mehrapi , can you please give a reference of the PR that you have created for this issue.
The better solution is to right `fixes #<issue_no>` in the commit and PR message.

**Comment by Mehrapi** [comment]
PR fixes issue #2200
