### ISSUE TITLE
Add Longest Palindromic Substring in JavaScript

### ISSUE THREAD

**Issue by izexi** [TheRenegadeCoder/sample-programs#2245]
To request a new code snippet, please fill out the following:

Project name: Longest Palindromic Substring
Project link: https://sample-programs.therenegadecoder.com/projects/longest-palindrome-substring/
Language: JavaScript

**Comment by MrAfrazKhan** [comment]
I am taking it.

**Comment by izexi** [comment]
> Some edge case are not handled in #2246 for this issue as explained in problem on renegade website, so I am taking it to handle them as well.
> EDIT: Please have a look at #2253 with all edge cases handled.

@MrAfrazKhan Not sure which edge cases you are referring to here, my code passes all the test cases as expected... whereas, your code doesn't (see the test below). Your code also doesn't return the specified format (see the test below).

```js
expect(longestPalStr('6eie6o6')).toBe('Longest Palindromic Substring is: 6eie6') // fails
expect(longestPalStr()).toBe('Incorrect input provided. Program Terminated') // fails
expect(longestPalStr('')).toBe('Incorrect input provided. Program Terminated') // fails
```
In addition to this, your code doesn't handle the input from the command line (by using `process.argv[2]`) which will cause the python runner test file to fail.

So... I'm not entirely sure why you decided to try and supersede this PR when my code is working as expected and your one... well it isn't.
