### ISSUE TITLE
Add Longest Word in String in JavaScript

### ISSUE THREAD

**Issue by barhouum7** [TheRenegadeCoder/sample-programs#2313]
This issue requests the addition of a code snippet to find the length of the longest word in a string using JavaScript.

Project name: find the length of the longest word in a string
Project link: https://sample-programs.therenegadecoder.com/projects/my-project-name
Language: JavaScript

**Comment by jrg94** [comment]
Cool idea! Keep in mind that for every idea you add, we'll need to document and add testing for it. We won't accept the code snippet without these requirements.

**Comment by barhouum7** [comment]
> Cool idea! Keep in mind that for every idea you add, we'll need to document and add testing for it. We won't accept the code snippet without these requirements.

Okay, I will add all the requirement to this idea. Otherwise, can you please explain to me what is the problem on this PR??
