### ISSUE TITLE
Add Sum All Primes in JavaScript

### ISSUE THREAD

**Issue by barhouum7** [TheRenegadeCoder/sample-programs#2314]
This issue requests the addition of a code snippet to determine sum all primes in JavaScript.

Project name: Sum all primes
Project link: https://sample-programs.therenegadecoder.com/projects/my-project-name
Language: JavaScript

**Comment by misterdabu** [comment]
I'd like to work on this issue please.

**Comment by barhouum7** [comment]
> I'd like to work on this issue please.

Yeah! Me too bro

**Comment by barhouum7** [comment]
@jrg94 I've added project documentation in this PR [#382](https://github.com/TheRenegadeCoder/sample-programs-website/pull/382)
