### ISSUE TITLE
Add Maximum Array Rotation in Python

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#2456]
Project name: Maximum Array Rotation
Project link: https://sample-programs.therenegadecoder.com/projects/maximum-array-rotation/
Language: Python

**Comment by harshitsuthar77731** [comment]
assign me

**Comment by 26tanishabanik** [comment]
I would like to work on this

**Comment by 26tanishabanik** [comment]
How can I write an article on my solution to the website?

**Comment by jrg94** [comment]
You can head over to the docs repo: https://github.com/TheRenegadeCoder/sample-programs-website

I can help you get started over there!
