### ISSUE TITLE
Add Transpose Matrix in Python

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#2472]
Project name: Transpose Matrix
Project link: https://sample-programs.therenegadecoder.com/projects/transpose-matrix/
Language: Python

**Comment by ssurbhi09** [comment]
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)


Is it?

**Comment by jrg94** [comment]
Do you want to solve it?

**Comment by ssurbhi09** [comment]
Yes please assign me 
If this is true!

**Comment by simran2002** [comment]
Pls assign this task to me.
