### ISSUE TITLE
Add Hello World in Scilab

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#257]
Wiki: https://en.wikipedia.org/wiki/Scilab

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by Tuntai** [comment]
hi... I am a newbie. need some help. I am not being able to find a folder for Scilab. Can you please tell me if I want to add the code snippet to resolve this issue, where to add it?

**Comment by jrg94** [comment]
This is a new program, so you would have to create the folder for us.
