### ISSUE TITLE
Add Fizz Buzz in Java

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#269]
Looking for someone to write Fizz Buzz in Java. I can do it, but I'll leave it open to the community.

**Comment by jashgala** [comment]
I can take this task up if it is available!

**Comment by jrg94** [comment]
It's all you 👍

**Comment by jrg94** [comment]
@jashgala is this still something you want to do?

**Comment by jrg94** [comment]
I decided to take this up.
