### ISSUE TITLE
Add Hello World in Mesa

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#273]
Wiki: https://en.wikipedia.org/wiki/Mesa_(programming_language)

**Comment by samdoj** [comment]
You can assign this to me if you like

**Comment by jrg94** [comment]
Feel free to assign yourself to things. I automatically assign myself out of habit, but I think you can assign yourself as a collaborator. Not sure if you can unassign me though...

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by jrg94** [comment]
This seems a bit of a stretch at the moment considering all I can find is information is an enormous manual that is a bit cumbersome. May revisit later.
