### ISSUE TITLE
Shebang in samplerunner.sh does not work for OSs without bash installed.

### ISSUE THREAD

**Issue by alope107** [TheRenegadeCoder/sample-programs#2940]
The shebang in `samplerunner.sh` is `#!/bin/bash` which works well for systems that have Bash installed. However, it does not work for systems (such as MacOS and other BSD-based systems) that do not have it installed by default.

`samplerunner.sh` does not use any features specific to Bash, so I propose we switch it to use `#!/bin/sh` instead. On most systems this will be symlinked to Bash anyway, but it will allow systems without Bash to work as well. Note that the proposed fix would NOT make any changes to code in the archive - because those run in Docker anyway nothing needs to change there.

Since this is a small, two-character change I'll just go ahead and open a PR for it and link this issue. Let me know what you think, and thanks for putting this fun repository together!

**Comment by rzuckerm** [comment]
Fixed with #2941
