### ISSUE TITLE
Add Rust Testing

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3004]
To request a new language, please fill out the following:

Language name: Rust
Official Language Style Guide: https://doc.rust-lang.org/1.0.0/style/README.html
Official Language Website: https://www.rust-lang.org/
Official Language Docker Image: https://hub.docker.com/r/_/rust

**Comment by rzuckerm** [comment]
The PR that is going to go with this issue is also going to have code changes since there are a lot of test failures for the Rust sample programs.

**Comment by jrg94** [comment]
I don't doubt it 😆
