### ISSUE TITLE
Weird Bug With Glotter Build

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#3070]
I assume this is a short term thing (like some dependency is down). On the off chance that it's not (like a dependency update broke Glotter), I figured I'd note it down here. I'll be attaching the log of the latest build shortly as well as the log of a recently working build for comparison.

**Comment by jrg94** [comment]
Okay, I literally can't attach the log because it's so large... (150 MB). Here are the dependency files at least.

- [Broken](https://github.com/TheRenegadeCoder/sample-programs/files/11402447/4_Install.Dependencies.txt)
- [Working](https://github.com/TheRenegadeCoder/sample-programs/files/11402450/4_Install.Dependencies.txt)

**Comment by jrg94** [comment]
Okay, looks like requests updated from 2.29 to 2.30. That definitely seems like a potential issue. Let me peek at their repo.

**Comment by jrg94** [comment]
Okay, the issue is definitely with requests as others are already seeing issues: https://github.com/psf/requests/issues/6443

**Comment by jrg94** [comment]
A short term fix would be to constrain requests to 2.29.0.

**Comment by jrg94** [comment]
Looks like there's more context here: https://github.com/psf/requests/issues/6432

**Comment by jrg94** [comment]
I might go the poetry route with our build system as mentioned here: https://github.com/psf/requests/issues/6432#issuecomment-1535048773. The lockfile idea sure seems ideal to prevent this exact situation.

**Comment by rzuckerm** [comment]
It looks like docker 6.1.0 is compatible with urllib3 2.0. Perhaps, that will fix this problem without having to pin back urllib3
