### ISSUE TITLE
Add Article for Fizz Buzz in PowerShell

### ISSUE THREAD

**Issue by Alcha** [TheRenegadeCoder/sample-programs#312]
I'll be writing this article but I wanted an issue posted for easier tracking.

**Comment by Alcha** [comment]
Oi, I forgot to post it to TheRenegadeCoder! I wrote one for [dev.to](https://dev.to) and posted it today, I'll fix it up for WordPress and get it over there now.

**Comment by Alcha** [comment]
Ahhh, I just realized the way I wrote the article wouldn't really suit the structure for your previous articles @jrg94. If you'd like to take a look at my current post and see if it's alright then I'll just post it on your site. Otherwise, I'll rework it to fit your structure and post it there as well.

For reference: https://dev.to/alcha/solving-the-fizz-buzz-problem-in-powershell-4a9l

**Comment by Alcha** [comment]
You got it! I'll go ahead and get an updated version complete tonight/tomorrow and post a draft on [TheRenegadeCoder][0].

[0]: https://therenegadecoder.com

**Comment by Alcha** [comment]
Well, it's definitely past `tonight/tomorrow`, but I can get this updated still.

I'm finally getting to my GitHub backlog of work, so I've marked this on my ToDo list and hope to complete it soon.

**Comment by jrg94** [comment]
Scheduled for 11/16 @ 10:00 AM Eastern: https://therenegadecoder.com/code/fizz-buzz-in-powershell/
