### ISSUE TITLE
Add Article for Hello World in Erlang

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#321]
See #320 for changes. Looking for author!

**Comment by nickkeers** [comment]
Hi @jrg94 happy to close this one up for you! What needs to be written for the Erlang hello world program? Some details on syntax, how to compile etc?

**Comment by jrg94** [comment]
Hey @nickkeers! Here's a list of our Hello World articles: https://sample-programs.therenegadecoder.com/projects/hello-world/

Then, if you need any details on how to get started, let me know!
