### ISSUE TITLE
Incorporate Solutions from wordcount Repo

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#327]
Recently, I [reached out](https://github.com/juditacs/wordcount/issues/97) to [Judit Acs](https://github.com/juditacs), the owner of the wordcount repo, about potentially incorporating their work into this repo. Unfortunately, the work is unlicensed, but they agreed to allow us to use their work.

That said, there are two major issues with this repo:

- All the scripts are optimized for performance which means they might not be ideal for this repo.
- I don't want to steal any work

As a result, we'll have to figure something out probably in a similar manner to #326.

**Comment by Alcha** [comment]
Personally, I think the fact that they're optimized for performance would make a great addition to the repository. We could have a note at the top of each file or even a separate folder within the language directory that specifies these aren't normal approaches to the problems, but instead focus on speed and performance overall.

I think it'd be great to have our standard sample programs that just show you how to use a language, while also having some that are focused on performance.

And actually, while writing this out, I realize that this may not actually mesh with the repo if you only wanted it to be a way to get sample programs, and not get too complicated. Ultimately, it's your decision as the repo owner, consider this my two ¢'s 😂
