### ISSUE TITLE
Add Longest Word in C#

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3319]
To request a new code snippet, please fill out the following:

Project name: Longest Word
Project link: https://sampleprograms.io/projects/longest-word
Language: C#

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by f3liz** [comment]
Hi, I would like to be assigned this please, thank you.

**Comment by rzuckerm** [comment]
@f3liz You are assigned

**Comment by alstondsouza1** [comment]
I would like to be assigned for this

**Comment by rzuckerm** [comment]
Sorry, @f3liz is already assigned
