### ISSUE TITLE
Add Remove All Whitespace in C#

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3324]
To request a new code snippet, please fill out the following:

Project name: Remove All Whitespace
Project link: https://sampleprograms.io/projects/remove-all-whitespace
Language: C#

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by alstondsouza1** [comment]
Hello, please assign me this problem.

**Comment by rzuckerm** [comment]
@alstondsouza1 You are assigned

**Comment by rzuckerm** [comment]
@alstondsouza1 There is already a "Remove all Whitespace in C#".
