### ISSUE TITLE
Add Convex Hull in Javascript

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3354]
To request a new code snippet, please fill out the following:

Project name: Convex Hull
Project link: https://sampleprograms.io/projects/convex-hull
Language: Javascript

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by GriffinAnnshual** [comment]
Hey @rzuckerm I would like to work on this issue.

**Comment by GriffinAnnshual** [comment]
Hey @rzuckerm I have made the PR, could you soon review it please?

**Comment by GriffinAnnshual** [comment]
Hi @rzuckerm I have fixed the issues could you review it please?
