### ISSUE TITLE
Add Insertion Sort in Commodore Basic

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3433]
To request a new code snippet, please fill out the following:

Project name: Insertion Sort
Project link: https://sampleprograms.io/projects/insertion-sort
Language: Commodore Basic

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by charandeepsinghb** [comment]
Please assign this to me.

**Comment by rzuckerm** [comment]
Sorry, @charandeepsinghb , I have already assigned it to me and have pushed a pull request.

**Comment by rzuckerm** [comment]
@charandeepsinghb If you would like to do a Commodore Basic program, I'd highly recommend taking a look at the [programs already done](https://github.com/TheRenegadeCoder/sample-programs/tree/main/archive/c/commodore-basic). I have figured out how to parse several different type of command-line arguments, and you are welcome to use anything that is in there as long as you reference me as the source. For example:
```basic
1 REM Command-line input processing done by rzuckerm
```

If you have any questions, you are welcome to join our [Discord channel](https://discord.gg/Jhmtj7Z).

**Comment by rzuckerm** [comment]
@charandeepsinghb If you do decide to contribute sample programs in Commodore Basic, please create a new issues, and I'll assign them to you. When I created the current issues, I didn't think that anyone but me would be interested in this language. I decided to only create issues for common languages (like C, C++, Java, etc.). Finally, I'd highly recommend reading our [Contributing Guide](https://github.com/TheRenegadeCoder/sample-programs/blob/main/.github/CONTRIBUTING.md).
