### ISSUE TITLE
Fix bad Typescript samples

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3484]
These Typescript samples are incorrectly named:

- [Palindromic-Number.ts](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/t/typescript/Palindromic-Number.ts)
- [Linear-Search.ts](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/t/typescript/Linear-Search.ts) - This is actually a prime number sample

**Comment by jrg94** [comment]
These are also causing issues locally for me.
