### ISSUE TITLE
Game of Life: GUI?

### ISSUE THREAD

**Issue by chrboe** [TheRenegadeCoder/sample-programs#356]
The [CONTRIBUTING](https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md) guidelines, the "Game of Life Rules" state that:

> 4. Simulation must be a GUI

What exactly does "GUI" refer to here? Do you mean an actual window (X11 or similar) or is graphical output in the terminal sufficient?

**Comment by jrg94** [comment]
I would prefer a window. I find that Game of Life is kind of ugly in the terminal using text or whatnot.

That said, it's really up to you. If you're using a lower-level language, there may not be a practical way to generate a GUI. In that case, I'm comfortable with a terminal solution.

**Comment by jrg94** [comment]
I believe we have three examples so far: Python, Java, and TypeScript.

**Comment by chrboe** [comment]
That's true, a terminal solution probably isn't the most visually appealing. The problem is that (as you correctly assumed) I'm looking at the cases of C and Go, which both don't really have a convenient way to create GUI applications.

The main problem is portability imo. As I'm running Linux, I could probably make something that works using X11 (or some kind of X11 binding for Go), but that would be kind of an ugly solution since it heavily relies on platform-specific code to work.

**Comment by jrg94** [comment]
I'm totally comfortable with a terminal solution in both of those languages.

**Comment by jrg94** [comment]
If you submit a solution, could you also update the contributing doc, so it makes more sense?
