### ISSUE TITLE
Add Transpose Matrix in Go

### ISSUE THREAD

**Issue by rzuckerm** [TheRenegadeCoder/sample-programs#3838]
To request a new code snippet, please fill out the following:

Project name: Transpose Matrix
Project link: https://sampleprograms.io/projects/transpose-matrix
Language: Go

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by vipin0** [comment]
Hi @rzuckerm Can you pls assign this to me ?

**Comment by rzuckerm** [comment]
@vipin0 Sorry, I forgot that you were assigned to this. @MeetThakur also submitted a PR, and it was approved and merged.

**Comment by vipin0** [comment]
No worries @rzuckerm !
