### ISSUE TITLE
Add Reverse String in X86 64

### ISSUE THREAD

**Issue by RMarx1456** [TheRenegadeCoder/sample-programs#3966]
To request a new code snippet, please fill out the following:

Project name: Reverse String
Project link: https://sampleprograms.io/projects/reverse-string/
Language: x86-64

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by rzuckerm** [comment]
@RMarx1456 You are assigned

**Comment by rzuckerm** [comment]
This is fixed. The PR was not filled out properly to automatically close it. It needs like this (for example):
```
I fixed #3966
```

**Comment by RMarx1456** [comment]
I will be sure to add that next time. Thank you for the info.
