### ISSUE TITLE
Add Duplicate Character Counter in C#

### ISSUE THREAD

**Issue by HumaGitGud** [TheRenegadeCoder/sample-programs#3969]
To request a new code snippet, please fill out the following:

Project name: Add Duplicate Character Counter in C#
Project link: https://sampleprograms.io/projects/duplicate-character-counter/
Language: C#

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by rzuckerm** [comment]
@HumaGitGud Please check the existing issues before adding a new one. There is already #3313 . I'll close this issue and assign you to that one.

**Comment by rzuckerm** [comment]
@HumaGitGud Please add a comment in #3313 , and I'll assign you. For some reason, it will not allow me to assign you unless you comment. Sorry!

**Comment by HumaGitGud** [comment]
@rzuckerm I commented in #3313 asking to claim the issue
