### ISSUE TITLE
Add Remove All Whitespace in C

### ISSUE THREAD

**Issue by qopci** [TheRenegadeCoder/sample-programs#3973]
To request a new code snippet, please fill out the following:

Project name: Remove All Whitespace 
Project link: https://sampleprograms.io/projects/remove-all-whitespace/
Language: C 

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide:
Official Language Website:
Official Language Docker Image: https://hub.docker.com/r/repository/image

**Comment by rzuckerm** [comment]
@qopci Please check the existing issues before creating a new one. Please add a comment in #3305 , and I'll assign you

**Comment by qopci** [comment]
Sorry, did not see it before, waiting for approval.
