### ISSUE TITLE
Add Remove All Whitespace in C++

### ISSUE THREAD

**Issue by LauraV-702** [TheRenegadeCoder/sample-programs#3974]
To request a new code snippet, please fill out the following:

Project name: Add Remove All Whitespace in C++
Project link: https://sampleprograms.io/projects/remove-all-whitespace/
Language: C++

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by rzuckerm** [comment]
@LauraV-702 Please check the existing issues before creating a new one. Please add a comment to #3338 , and I'll assign you.

**Comment by LauraV-702** [comment]
Apologies, I'll double check that next time, thank you.
