### ISSUE TITLE
Potential Collab?

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#398]
Jokingly, of course.. kinda..

Anyway, found another amazing "in every language" repo: https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books

**Comment by Stargator** [comment]
@jrg94 I didn't want to create a new issue, but could you drop me from the collaborator list so I don't get notified of everything in this repo?

**Comment by jrg94** [comment]
Hey @Stargator. You have full control over whether or not you receive notifications from this repo. In fact, you’re not on the collaborators list. You probably hit ‘watch’ at the top of the repo. Check there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
