### ISSUE TITLE
Add Article for Fizz Buzz in Java

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#400]
See #399

**Comment by stuin** [comment]
Writing an article for Fizz buzz in Befunge would be weird to do first. I shall take this one then.

**Comment by jrg94** [comment]
Hey @stuin! I'm actually in the process of transferring all the articles from my site to this repo. I noticed you were doing some editing on my site. Any chance you could move some of your work to the `docs/projects/fizz-buzz/_posts` folder? You can add the _posts folder if it doesn't exist. 

You're still welcome to post on my site, but I'll be duplicating the work here and referencing the article from the my site.
