### ISSUE TITLE
Add Binary Search in Ruby

### ISSUE THREAD

**Issue by tgillysuit** [TheRenegadeCoder/sample-programs#4000]
To request a new code snippet, please fill out the following:

Project name: binary-search
Project link: https://sampleprograms.io/projects/binary-search
Language: Ruby

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: https://ruby-style-guide.shopify.dev/
Official Language Website: https://www.ruby-lang.org/en/
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by rzuckerm** [comment]
@tgillysuit You are assigned

**Comment by tgillysuit** [comment]
thank you!
