### ISSUE TITLE
Add Duplicate Character Counter in Swift

### ISSUE THREAD

**Issue by Lizock** [TheRenegadeCoder/sample-programs#4014]
Project name: Duplicate Character Counter
Project link: https://sampleprograms.io/projects/duplicate-character-counter
Language: Swift

**Comment by rzuckerm** [comment]
@Lizock Which project are you planning on doing Duplicate Character Counter or Dijkstra?

**Comment by Lizock** [comment]
I am sorry, I was going to do a Duplicate Character Counter.

**Comment by rzuckerm** [comment]
@Lizock You are assigned, good luck!

**Comment by rzuckerm** [comment]
Also, I updated the project link. Please see that link for details on the project requirements and tests that are done.
