### ISSUE TITLE
Add Longest Word in TypeScript

### ISSUE THREAD

**Issue by Jameson789** [TheRenegadeCoder/sample-programs#4025]
To request a new code snippet, please fill out the following:

Project name: Add Longest Word in TypeScript
Project link: https://sampleprograms.io/projects/longest-word/
Language: Typescript

**Comment by rzuckerm** [comment]
@Jameson789 We already have a sample for [Longest Word in Typescript](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/t/typescript/longest-word.ts).
