### ISSUE TITLE
Is it Okay to Add Other Sample Programs?

### ISSUE THREAD

**Issue by Noah11012** [TheRenegadeCoder/sample-programs#403]
Currently each language has a maximum of four sample programs:

- Hello World
- Reverse String
- Fizz Buzz
- Game of Life

Is it okay to add other sample programs such as showing how to read and write files in a language?

**Comment by jrg94** [comment]
Hey, Noah! You're welcome to add any solution you want. All I ask is that you write up a formal description of what your code does, so we can keep them consistent for every language. Check out the [contributing doc](https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md) for examples.
