### ISSUE TITLE
Add Longest Word in C#

### ISSUE THREAD

**Issue by BahramT1** [TheRenegadeCoder/sample-programs#4032]
To request a new code snippet, please fill out the following:

Project name: Longest Word
Project link: https://sampleprograms.io/projects/longest-word/c-sharp/
Language: C#

**Comment by rzuckerm** [comment]
@BahramT1 We already have a [sample program](https://github.com/TheRenegadeCoder/sample-programs/blob/main/archive/c/c-sharp/LongestWord.cs) for this. In general, you change check the README.md file for a particular language to see what samples are needed. This is all spelled out in our [Contributing Guide](https://github.com/TheRenegadeCoder/sample-programs/blob/main/.github/CONTRIBUTING.md)
