### ISSUE TITLE
Page Not Found - Registration Missing on Renegade Color

### ISSUE THREAD

**Issue by Noah11012** [TheRenegadeCoder/sample-programs#404]
The link in CONTRIBUTION.md under section Articles, "create an account" is broken.

Broken link: https://therenegadecoder.com/membership-join/membership-registration/

**Comment by jrg94** [comment]
True! Here's the updated link, and I'll take care of that issue now: https://therenegadecoder.com/members/registration/

**Comment by jrg94** [comment]
For reference: https://github.com/TheRenegadeCoder/sample-programs/commit/fda606b58073f5502dab520069e1f1403aea22bd
