### ISSUE TITLE
Add a Palindromic Number in Swift

### ISSUE THREAD

**Issue by KaalidArare** [TheRenegadeCoder/sample-programs#4044]
To request a new code snippet, please fill out the following:

Project name: Palindromic Number
Project link: https://github.com/TheRenegadeCoder/sample-programs/pull/4033
Language: Swift

If this code snippet will also be the first in a new language, please fill out the following:

Official Language Style Guide: 
Official Language Website: 
Official Language Docker Image: https://hub.docker.com/r/repository/image 

> The project link must be a link to a project on the [Sample Programs Website project list][sample-programs-project-list].
> If you would like to add a new project to the Sample Programs Website,
> please first make a pull request to the [Sample Programs Website][sample-programs-website].

[sample-programs-website]: https://github.com/TheRenegadeCoder/sample-programs-website
[sample-programs-project-list]: https://sampleprograms.io/projects/

**Comment by KaalidArare** [comment]
No worries I apologize. I was looking for the issue you referred to me but
was having hard time finding it. I would appreciate if you can send me the
link. Thank you!

**Comment by rzuckerm** [comment]
https://github.com/TheRenegadeCoder/sample-programs/issues/4041 , which is closed now
