### ISSUE TITLE
Add Longest Word in Ruby

### ISSUE THREAD

**Issue by BahramT1** [TheRenegadeCoder/sample-programs#4046]
To request a new code snippet, please fill out the following:

Project name: Longest Word
Project link: https://sampleprograms.io/projects/longest-word/
Language: Ruby

**Comment by rzuckerm** [comment]
@BahramT1 Please check the existing issues before adding a new one. This [issue](https://github.com/TheRenegadeCoder/sample-programs/issues/4007) already exists
