### ISSUE TITLE
Add Article for Python File IO

### ISSUE THREAD

**Issue by Noah11012** [TheRenegadeCoder/sample-programs#411]
See #410

**Comment by Noah11012** [comment]
If you get multiple submissions for my article, sorry about that. Sometimes I accidentally click the button instead of the preview button.

**Comment by jrg94** [comment]
I'm looking this over at the moment!

**Comment by jrg94** [comment]
Alright, take a look at my edits and let me know if you're comfortable with them! I'm scheduling your article for November 2nd, 2018.
