### ISSUE TITLE
Add Hello World in Lux

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#44]
Found another open-source functional language: https://github.com/LuxLang/lux

**Comment by jrg94** [comment]
Found a snippet. I'd like to simplify it when I have time:

```
(;module: {#;doc "This will be our program's main module."}
  lux
  (lux (codata io)
       [cli #+ program:]))

(program: args
  (io (log! "Hello, world!")))
```

**Comment by jrg94** [comment]
Also, here are some docs for the README: https://legacy.gitbook.com/book/luxlang/the-lux-programming-language/details

**Comment by k1dnyy** [comment]
Can I take this issue up??

**Comment by jrg94** [comment]
It's all you!

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by Ask-Subhasmita** [comment]
@jrg94 Hi, I've put up a pull request regarding the same you can check and let me know if something needs to be changed. Thank You  😊
