### ISSUE TITLE
Reevaluate Milestones

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#441]
## Milestones

250 Snippets & 100 Articles before the end of the year.

## Summary

With 103 days left in the year, will we actually hit these goals? Current totals:

```
Snippets: 142
Articles: 48 Published & 5 Scheduled through November 5th
```

We can probably hit our 250 snippets goal. We just need to hit roughly a snippet a day until the end of the year. Articles are unlikely. I'd be surprised if we hit 75.

**Comment by martyav** [comment]
Perhaps this can help: [Hacktoberfest](https://hacktoberfest.digitalocean.com/#hacktoberfest).

We just need to add the hacktoberfest tag to issues to attract some attention.

**Comment by jrg94** [comment]
Update: there are 91 days left in the year and were at 150 snippets. Roughly one a day to the end of the year. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
We're up to 166 snippets as of 10/10/18. That leaves us with 82 days to complete 84 code snippets. I think we're right on track!

Articles are another issue. I think I'm going to bump back the deadline to June of next year. That may still be a little early as we can only get maybe 2 articles a week out at the moment. I think 2/month is our going rate, and we're at 50 as of today. We'll be lucky to hit 60 by the end of the year.

At any rate, I think we can close this issue for now.
