### ISSUE TITLE
Add Algorithms

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#448]
I’m taking an algorithms class, and I’d like to have some more practice on some of the algorithms. So, I might include a few like:

- Convex Hull
- Longest Subsequence
- Shortest Path
- ~~Fibonacci~~
- Matrix Chaining
- Closest Pair
- Paragraphing
- Job Scheduling
- Luhn Algorithm
- Huffman Codes
- etc.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Noah11012** [comment]
Cool! I'm taking a course and reading a book on algorithms and data structures.

**Comment by jrg94** [comment]
That's awesome! I have a midterm next week, and I need to brush up on my Divide and Conquer and Dynamic Programming algorithms.

**Comment by chrboe** [comment]
> * Fibonacci

Great idea! I've been wanting to suggest that

**Comment by jrg94** [comment]
Yeah, Fibonacci is actually an example of dynamic programming despite its simplicity, so I figured it would make a nice addition. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Closing this issue. All future algorithms will get their own issues.

**Comment by jpvg10** [comment]
@jrg94 Hey so I'm not familiar with some of these but I could take Factorial or Job Scheduling (if it is what I think it is). Let me know!

**Comment by jrg94** [comment]
Factorial would be great! The description should be similar to fibonacci. The algorithm should accept a number on the command line and output the factorial of that number. There needs to be some error case for numbers less than 0, but that's it!

**Comment by jrg94** [comment]
Job scheduling is a bit more complex because the directions vary a lot (i.e. number of machines, different goals, etc.).

**Comment by jpvg10** [comment]
Ok I'll take factorial then. One thing about it is that n! grows really quick so it will overflow integers on small values of n (can't remember the exact limits right now). 

So should we mention this, or maybe give some constraints to the input to avoid it?

**Comment by jrg94** [comment]
It depends. I know that we've been limiting values for fibonacci. Though, I'm not sure we mention anything about limits in the contributing doc. Perhaps that's an area of improvement.

**Comment by chrboe** [comment]
I think something like "You should impose a limit so that the largest generated number still fits into your language's largest supported datatype" might be an appropriate guideline here. Like you mentioned, some languages don't have a limit on integer size, while others – think Brainfuck with its 8 bit cells – are fairly limited.

**Comment by jpvg10** [comment]
Yeah for example a Java `int` is 32 bits and a `long` is 64 bits. So I think leaving the limit up to the user is a good idea, because it depends on the language and data type they choose. I'll write it then!
