### ISSUE TITLE
Add Article for Reverse String in Ruby

### ISSUE THREAD

**Issue by Noah11012** [TheRenegadeCoder/sample-programs#455]
See #454

**Comment by jrg94** [comment]
I see you're done with this. I haven't had a chance to review it yet (two midterms this week). Just letting you know I saw it!

**Comment by jrg94** [comment]
Finally caught up to this! Scheduled for November 23rd, 2018 @ 10:00 AM.

Here's the link: https://therenegadecoder.com/code/reverse-a-string-in-ruby/
