### ISSUE TITLE
Add Article for Fizz Buzz in Swift

### ISSUE THREAD

**Issue by martyav** [TheRenegadeCoder/sample-programs#482]
Added code snippet but need to add article as well

**Comment by martyav** [comment]
I just submitted my first draft

**Comment by jrg94** [comment]
Awesome! I just got around to taking a look.

**Comment by jrg94** [comment]
So far so good! I took a quick look and added in some headings. I recommend breaking up your main section into subheadings if possible. 

Also, it may be a good idea to display chunks of your code as you go. For instance, you reference the various lines of code throughout your explanation, Why not copy that line out into it's own code block to further illustrate your point? I've added a sample under your line 2 section.

Of course, it's up to you how you want to approach the article. I just ask that you keep a similar structure. 👍 Nice work, by the way! You really gave a lot of detail which I think is great. Also, you add a lot of personality to you're writing which I think will allow others to connect with your work.

**Comment by martyav** [comment]
Thank you. October has been very busy. I'll try to finish by this week

**Comment by martyav** [comment]
Updated with headings, and the two subsections on running the code, and renegade coder's project. filled out.

**Comment by jrg94** [comment]
All done! Thanks again for taking care of this. I appreciate it.
