### ISSUE TITLE
Add Convex Hull Problem Description to Contributing Doc

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#507]
After adding longest common subsequence, I've decided to open up a series of issues to the community. Would someone like to come up with a problem description for convex hull and add it to the [contributing doc](https://github.com/TheRenegadeCoder/sample-programs/blob/master/CONTRIBUTING.md)?

**Comment by jpvg10** [comment]
I would like to take this issue. So the idea is to write a description and an example of the convex hull, not to implement the algorithm. Right?

**Comment by jrg94** [comment]
Yeah you can take a look at the other examples, but that’s the idea. You want to make it generic enough that it can be comfortably implemented in as many languages as possible. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
