### ISSUE TITLE
Add Fizz Buzz in Kotlin

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#511]
If this is your first time contributing, create the Fizz Buzz file in the appropriate directory and add the name of the program to the Sample Programs section of the language README. Then, create a new issue for its article like #30. Link this issue in the README and create a pull request when you're done.

**Comment by ali-abdullah** [comment]
Hey, I went ahead created a PR for this issue. Hope you don't mind not discussing it first.

**Comment by ali-abdullah** [comment]
@jrg94  Hey, I went ahead created a PR for this issue. Hope you don't mind not discussing it first.

**Comment by jrg94** [comment]
Not a problem!
