### ISSUE TITLE
Add File IO in Haskell

### ISSUE THREAD

**Issue by auroq** [TheRenegadeCoder/sample-programs#596]

**Comment by jrg94** [comment]
Hey @auroq! You've pushed Haskell to the top 5 languages in the repo. I like having a functional language up there. That's pretty cool.

**Comment by auroq** [comment]
Wow. That's really cool! I'm still fairly new to functional languages myself, so I'm really happy I can share my somewhat limited knowledge. It's been a good opportunity for me to solidify some of the basics.
