### ISSUE TITLE
Add Hello World in Gambit

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#763]
See: https://github.com/gambit/gambit

**Comment by beebus** [comment]
More information:
[https://en.wikipedia.org/wiki/Gambit_(scheme_implementation)](url)

**Comment by beebus** [comment]
FYI, I tried the installation instructions for Gambit at [https://github.com/gambit/gambit](url), but my Ubuntu laptop (4GB RAM) got held up for about an hour at the `make -j8` step. Gave up.

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by jrg94** [comment]
Not a ton to work with in terms of documentation.
