### ISSUE TITLE
Add Sorting Algorithms

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#789]
How have we not added an sorting algorithms? Let's get this going!

- Bubble Sort
- Selection Sort
- Quick Sort
- Merge Sort

**Comment by auroq** [comment]
@jrg94, I'd be happy to do at least part of the work for this ticket. I started on Bubble Sort, and just pushed a branch called "sorting." I'd still like to add some information about performance, but take a look and let me know what you think.

I also thought, it might make sense to put all sorting algorithms in a subset of projects, so next to all the other project document links (rot-13, game of life, hello-world, etc..) we have a link for sorting algorithms, that takes us to a similar page that lists all the sorting algorithms we decide to document.

**Comment by Alcha** [comment]
One thing that's possible (depending on a few things) would be to change the organization to be based on the various programs we have written. Then under the **Fizz Buzz* directory we have our standard alphabet of languages that have that script implemented.

Then the README could contain information on the programs we aim to incorporate in every langaue and which languages have created them.

**Comment by Alcha** [comment]
By README I mean the root README of the project. Or instead even the wiki to help with this.

**Comment by jrg94** [comment]
Let's get a pull request going, so we can do a proper review!

**Comment by auroq** [comment]
Alright. Shall I split this issue into one issue per algorithm as well? Then we can have each pull request reference an issue.

**Comment by jrg94** [comment]
Yeah, that's probably a good plan. I created this issue as more of a spur of the moment idea. We can get more specific now.

**Comment by auroq** [comment]
Closing as this has been split into #790, #791, #792, and #793.
