### ISSUE TITLE
Add Selection Sort to Projects

### ISSUE THREAD

**Issue by auroq** [TheRenegadeCoder/sample-programs#791]
See #789

**Comment by auroq** [comment]
@jrg94, for selection sort, do we want to have implementations for the algorithm using two lists or do we want in place sorting (with element swapping)? Or should I add an explanation of both to the document and let the author decide based on language?

**Comment by jrg94** [comment]
At the end of the day, the solution has to be executable. How the sorting is performed doesn't really matter so much as the result is sorted. Of course, the algorithm matters, but I think we're going to eventually allow multiple solutions to the same problem (see #635). I just haven't figured out how to support that yet.
