### ISSUE TITLE
Milestone Update

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#802]
Since it's December, I figured we should probably revisit our milestones and determine if we're going to hit them. 

As of today, the nearest milestone is is the 250 snippets which I'm hoping to hit by the end of the year. According to the [wiki](https://github.com/TheRenegadeCoder/sample-programs/wiki/Alphabetical-Language-Catalog), we have 217 code snippets in this repo. That means, we'll need to average roughly one snippet per day to get this done. I think we can do that!

As for the article milestone, I bumped it back to June next year (#441), but I actually think we can push it back up. Currently, the new website contains 29 articles according to its [homepage](https://sample-programs.therenegadecoder.com/). By no means could we hit 100 articles normally, but it turns out we already have 100. They just need to be transitioned from the old site. Perhaps we could hit that goal as well.

**Comment by jrg94** [comment]
I've added everyone on this who has been helping lately.

**Comment by Alcha** [comment]
If I get some free time I'll look at the Issues and see what I can't come up with. I'm currently swamped with a few other projects as well so I'm not able to promise anything.

If anything comes of it, I'll update the respective issues/submit a PR as usual.

**Comment by jrg94** [comment]
No sweat! Take care of yourself. 👍

**Comment by auroq** [comment]
I have a few questions. What exactly counts as an article? Is it just articles describing an implementation in a language? Or does it also include our documentation as well (i.e. https://sample-programs.therenegadecoder.com/projects/hello-world/)?

What is needed to get these transitioned? Could we transition them all in time for the milestone if we move it back up?

If so, I see no reason why we can't move the milestone back and just focus on transitioning articles.

**Comment by jrg94** [comment]
That’s a great question! My understanding is that Jekyll only categorizes files in the _posts folders as articles. Everything else is a page. 

In other words, transitioning articles would be enough to hit out goal. I’m cool with moving up the deadline if that’s what we want to target until the end of the year.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
Also, to answer your other question, transitioning is sort of painful right now. You basically have to copy all the content from the original article into markdown by hand. You can see an example from my most recent pull request.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jrg94** [comment]
With just over 10 days left in the year, I'd like to revisit these milestones one last time. Currently, we have 223 code snippets which is 27 shy of our goal. To make that happen, we'd need to share nearly 3 snippets a day, so I'm not sure that one is going to happen.

As for the article goal, we're sitting at 38/100. Granted, I've just gotten enough free time to start working again.

I'll keep transitioning articles. If anyone wants to help, let me know!

**Comment by jrg94** [comment]
Alright, we have 3 days left! We're about 12 away from hitting the 250 snippets goal. I think for the time being, I'm going to help with that. Then, I'll shift back and see if I can finish the articles.

**Comment by jrg94** [comment]
I've decided to hold off on the article transition until sometime next year. As it turns out, writing the release table is incredibly time consuming and painful. Instead, there are some fixes I'd like to make to the wiki generator. In addition, I'd like to write my own release generator, so I don't have to craft that table by hand every time.  

Let's get to 250 snippets today. Then, I'll polish off the release, so we can take a bit of a break.

**Comment by jrg94** [comment]
There's 5/7 completed! Just 2 more. 👍

**Comment by jrg94** [comment]
Great job, everyone! I've written up the official release for [250 code snippets](https://github.com/TheRenegadeCoder/sample-programs/releases/tag/250-snip). Next stop, 100 articles.
