### ISSUE TITLE
Add Article for Even Odd in Python

### ISSUE THREAD

**Issue by auroq** [TheRenegadeCoder/sample-programs#849]
See #848

**Comment by beebus** [comment]
It appears this issue has been taken care of and should be closed?
[https://github.com/TheRenegadeCoder/sample-programs/pull/939](url)
[https://github.com/TheRenegadeCoder/sample-programs/blob/master/archive/p/python/even_odd.py](url)

**Comment by jrg94** [comment]
Hey @beebus. This didn't actually get merged, so it's still opened. If you check the project page, there's no article for it: https://sample-programs.therenegadecoder.com/projects/even-odd/.
