### ISSUE TITLE
Add Article for Reverse a String in JavaScript

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#93]
Merged in the code: #92.

Now, I know I was struggling with this series when I finished implementing reverse a string in C# (#80). But, things just got worse. JavaScript only runs in a web environment, so I can't possibly use a command line.

Also, besides using a library, it doesn't appear to be easy to create a general case string reversal algorithm in JavaScript. Though, I suppose that's the point of this series. I've added an asterisk to the implementation's README.

**Comment by jrg94** [comment]
@trevershick pointed out that we can just use Node to run JavaScript on the command line. The script has been updated to reflect that: #139

**Comment by Alcha** [comment]
Just a small note since you mentioned not being able to use a console, you can fire up chrome and open the dev tools to use the console there.

**Comment by jrg94** [comment]
Of course, the distinction I was trying to make was between the environments. You have to run some sort of web environment to run JavaScript. Node is an alternative which you can run right from your local command line.

**Comment by Alcha** [comment]
Ahhh, perfect, I'm a huge fan of Node.js and prefer it for anything Javascript anyway 😊
