### ISSUE TITLE
Add Hello World in Janet

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#947]
GitHub just very nicely recommended [Janet](https://github.com/janet-lang/janet) to me. Anyone want to take a stab at it?

**Comment by pandabear41** [comment]
I can do this one. Also will add some other Janet examples.

**Comment by jrg94** [comment]
Great! Thanks @pandabear41.

**Comment by pandabear41** [comment]
I got the hello world built. Been exploring how to get command line arguments for some other examples (the methods I know in lisp don't work in Janet). 

I have fibinocci so far in my fork under 
2b2f1ca82c69b4c265a76ae0ba43b92e494f3052, but I don't feel it is ready yet and I want to figure out how to get command line args.

**Comment by jrg94** [comment]
No sweat! Worst case scenario, we can incorporate the solutions with some hardcoded or user input based examples. Ideally, the language would need command line support for us to hook it into our test suite, however.
