### ISSUE TITLE
Add Hello World in Hackett

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/sample-programs#967]
See: https://github.com/lexi-lambda/hackett

**Comment by apurav10** [comment]
i wanna work on it.

**Comment by jrg94** [comment]
Please make sure the program follows these guidelines: https://sample-programs.therenegadecoder.com/projects/hello-world/

**Comment by jrg94** [comment]
Couldn't find a working hello world script for this language, so closing out for now.
